---
- name: Deploy Next.js and Nest.js on Nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Install Next.js and Nest.js project dependencies
      command: npm install
      args:
        chdir: /var/www/nextjs

    - name: Build Next.js project
      command: npm run build
      args:
        chdir: /var/www/nextjs

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
