---
- name: Install Node.js and npm on Red Hat-based systems
  hosts: webservers
  become: yes
  tasks:
    - name: Install PM2 process manager
      npm:
        name: pm2
        global: yes
      become: yes
    # - name: Install npm & nodejs
    #   yum:
    #     name:
    #       - nodejs
    #       - npm
    #     state: present
    - name: Install Git on CentOS/RHEL
      become: yes
      yum:
        name: git
        state: present
    - name: Clone the Next.js and Nest.js repositories
      git:
        repo: https://github.com/akanshakaranjkhele00/poc.git
        dest: /var/www/nextjs
      become: yes

    - name: Install Next.js and Nest.js project dependencies
      command: npm install
      args:
        chdir: /var/www/nextjs/Frontend
    - name: Build Next.js project
      command: npm run build
      become: yes
      args:
        chdir: /var/www/nextjs/Frontend
      async: 3600
      poll: 0
    - name: Start the Next.js application
      command: npm run dev
      args:
        chdir: /var/www/nextjs/Frontend
      async: 3600
      poll: 0

    - name: Install  Nest.js project dependencies
      command: npm install
      args:
        chdir: /var/www/nextjs/Backend
      async: 3600
      poll: 0
    - name: Build Nest.js project
      command: npm run build
      become: yes
      args:
        chdir: /var/www/nextjs/Backend
      async: 3600
      poll: 0
    - name: Run Next.js project
      command: npm run start
      become: yes
      args:
        chdir: /var/www/nextjs/Backend
      async: 3600
      poll: 0
    - name: code Lint
      command: npm run lint
      become: yes
      args:
        chdir: /var/www/nextjs/Frontend
    # - name: sonarqube
    #   run: |

    #     npm install -g sonarqube-scanner
    #     sonar-scanner \
    #     -Dsonar.host.url="http://51.20.98.83:9000 " \
    #     -Dsonar.login=admin \
    #     -Dsonar.password=admin \
    #     -Dsonar.projectKey="Demo_POC" \
    #     -Dsonar.source=.
