---
- name: Install Node.js and npm on Red Hat-based systems
  hosts: webservers
  become: yes
  tasks:
    - name: Install npm
      yum:
        name:
          - nodejs
          - npm
        state: present
    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Install Git on CentOS/RHEL
      become: yes
      yum:
        name: git
        state: present
    - name: Clone the Next.js and Nest.js repositories
      git:
        repo: https://github.com/akanshakaranjkhele00/poc.git
        dest: /var/www/nextjs
      become: yes
    - name: Install Next.js and Nest.js project dependencies
      command: npm install
      args:
        chdir: /var/www/nextjs/Frontend

    - name: Build Next.js project
      command: npm run build
      become: yes
      args:
        chdir: /var/www/nextjs/Frontend
    - name: Create an Nginx configuration file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d
      tags:
        - nginx
    - name: Reload Nginx to apply the new configuration
      service:
        name: nginx
        state: reloaded
      tags:
        - nginx
