---
- name: Install Node.js and npm on Red Hat-based systems
  hosts: webservers
  become: yes
  tasks:
    - name: Install npm
      yum:
        name:
          - nodejs
          - npm
        state: present
    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes
