---
- name: Install Node.js and npm on Red Hat-based systems
  hosts: webservers
  become: yes
  tasks:
    - name: Install PM2 process manager
      npm:
        name: pm2
        global: yes
      become: yes
    # - name: Install npm & nodejs
    #   yum:
    #     name:
    #       - nodejs
    #       - npm
    #     state: present
    - name: Install Git on CentOS/RHEL
      become: yes
      yum:
        name: git
        state: present
    - name: Clone the Next.js and Nest.js repositories
      git:
        repo: https://github.com/akanshakaranjkhele00/poc.git
        dest: /var/www/nextjs
      become: yes

    # - name: Install Next.js and Nest.js project dependencies
    #   command: npm install
    #   args:
    #     chdir: /var/www/nextjs/Frontend
    # - name: Build Next.js project
    #   command: npm run build
    #   become: yes
    #   args:
    #     chdir: /var/www/nextjs/Frontend
    # - name: Start the Next.js application
    #   command: npm run dev
    #   args:
    #     chdir: /var/www/nextjs/Frontend
    #   async: 3600
    #   poll: 0

    - name: Install  Nest.js project dependencies
      command: npm install
      args:
        chdir: /var/www/nextjs/Backend
    - name: Build Nest.js project
      command: npm run build
      become: yes
      args:
        chdir: /var/www/nextjs/Backend
    - name: Run Next.js project
      command: npm run start
      environment:
        PORT: 4567 # Specify the desired port here
      become: yes
      args:
        chdir: /var/www/nextjs/Backend
      async: 3600
      poll: 0

