---
- name: Deploy Artifact from Nexus to Nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Download artifact from Nexus(Backend)
      get_url:
        url: "http://51.20.74.221:8081/repository/myorg-npm-group-repo/dist/-/dist-1.0.0.tgz"
        dest: "/var/artifact"
        force: yes
      become: yes

    - name: Download artifact from Nexus(Frontend)
      get_url:
        url: "http://51.20.74.221:8081/repository/myorg-npm-group-repo/frontend/-/frontend-0.1.0.tgz"
        dest: "/var/artifact"
        force: yes
      become: yes

    # - name: Extract the tgz file
    #   ansible.builtin.shell:
    #     cmd: "tar -xvzf /var/artifact/microservice-0.0.1.tgz -C /var/artifact/pack"
    # - name: Extract the tgz file
    #   ansible.builtin.shell:
    #     cmd: "tar -xvzf /var/artifact/poc_final-0.1.0.tgz -C /var/artifact/pack"

    # - name: Replace apiKey in next.config.js
    #   ansible.builtin.lineinfile:
    #     path: /var/artifact/pack/package/next.config.js
    #     regexp: '^\\s*apiKey:\\s*'
    #     line: '    apiKey: "http://51.20.254.144:3000/",'

    # - name: Replace productKey in next.config.js
    #   ansible.builtin.lineinfile:
    #     path: /var/artifact/pack/package/next.config.js
    #     regexp: '^\\s*productKey:\\s*'
    #     line: '    productKey: "http://51.20.254.144:3000/products/name",'

    # - name: Copy the new file to the target folder
    #   ansible.builtin.copy:
    #     src: /var/artifact/next.config.js
    #     dest: /var/artifact/pack/package/next.config.js
    #     remote_src: yes
    #     backup: yes
    # - name: Build  project
    #   command: npm run build
    #   become: yes
    #   args:
    #     chdir: /var/artifact/pack/package
    #   async: 3600
    #   poll: 0

    # - name: Run  project
    #   command: npm run start
    #   become: yes
    #   args:
    #     chdir: /var/artifact/pack/package
    #   async: 3600
    #   poll: 0

    # - name: Copy artifact to Nginx directory
    #   ansible.builtin.copy:
    #     src: "/var/artifact/pack"
    #     dest: "/usr/share/nginx/html/"
    #     remote_src: yes

    # - name: Restart Nginx
    #   systemd:
    #     name: nginx
    #     state: restarted
