---
- name: Deploy Artifact from Nexus to Nginx
  hosts: webservers
  become: yes
  tasks:

    - name: Download artifact from Nexus(Backend)
      get_url:
        url: "http://51.20.74.221:8081/repository/myorg-npm-group-repo/poc_final/-/poc_final-0.1.0.tgz"
        dest: "/var/artifact"
        force: yes
      become: yes
      
    - name: Download artifact from Nexus(Frontend)
      get_url:
        url: "http://51.20.74.221:8081/repository/myorg-npm-group-repo/microservice/-/microservice-0.0.1.tgz"
        dest: "/var/artifact"
        force: yes
      become: yes


    - name: Extract the tgz file
      ansible.builtin.shell:
        cmd: "tar -xvzf /var/artifact/microservice-0.0.1.tgz -C /var/artifact/pack"
    - name: Extract the tgz file
      ansible.builtin.shell:
        cmd: "tar -xvzf /var/artifact/poc_final-0.1.0.tgz -C /var/artifact/pack"

    - name: Add environment variables to your Next.js application's environment file
      lineinfile:
        path: /var/artifact/pack/package/next.config.js
        line: "apiKey=http://51.20.254.144:3000/"

    - name: Add environment variables to your Next.js application's environment file
      lineinfile:
        path: /var/artifact/pack/package/next.config.js
        line: "productKey=http://51.20.254.144:3000/products/name"

        


   

    - name: Copy artifact to Nginx directory
      ansible.builtin.copy:
        src: "/var/artifact/pack"
        dest: "/usr/share/nginx/html/"
        remote_src: yes

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
