---
- name: Deploy Artifact from Nexus to dev
  hosts: webservers
  become: yes
  tasks:
    - name: Install PM2 process manager
      npm:
        name: pm2
        global: yes
      become: yes
    - name: Download artifact from Nexus
      get_url:
        url: "http://51.20.74.221:8081/repository/myorg-raw-hosted-repo/app.tar.gz"
        dest: "/var/artifact"
        force: yes
      become: yes

    # - name: Extract the tgz file
    #   ansible.builtin.shell:
    #     cmd: "tar -xvzf /var/artifact/frontend/frontend-0.1.0.tgz -C /var/artifact/frontend"
    # - name: Extract the tgz file
    #   ansible.builtin.shell:
    #     cmd: "tar -xvzf /var/artifact/backend/dist-1.0.0.tgz -C /var/artifact/backend"

    # - name: Copy the new file to the target folder
    #   ansible.builtin.copy:
    #     src: /var/artifact/next.config.js
    #     dest: /var/artifact/frontend/package/next.config.js
    #     remote_src: yes

    # - name: Set permissions on Frontend directory
    #   command: sudo chmod 777 /var/artifact/frontend/package
    #   become: yes
    # - name: Set permissions on Backend directory
    #   command: sudo chmod 777 /var/artifact/backend/package
    #   become: yes

    # - name: Install Next.js
    #   command: npm install
    #   args:
    #     chdir: /var/artifact/frontend/package
    # - name: Build Next.js project
    #   command: npm run build
    #   become: yes
    #   args:
    #     chdir: /var/artifact/frontend/package
    #   async: 3600
    #   poll: 0
    # - name: Start the Next.js application
    #   command: npm run dev
    #   args:
    #     chdir: /var/artifact/frontend/package
    #   async: 3600
    #   poll: 0

    # - name: Install  Nest.js
    #   command: npm install
    #   args:
    #     chdir: /var/artifact/backend/package
    #   async: 3600
    #   poll: 0
    # - name: Build Nest.js project
    #   command: npm run build
    #   become: yes
    #   args:
    #     chdir: /var/artifact/backend/package
    #   async: 3600
    #   poll: 0
    # - name: Run Next.js project
    #   command: npm run start
    #   become: yes
    #   args:
    #     chdir: /var/artifact/backend/package
    #   async: 3600
    #   poll: 0
